### ISSUE TITLE
hugo-installer is not able to verifyBinaryHealth

### ISSUE THREAD

**Issue by simonstumpf** [dominique-mueller/hugo-installer#55]
The hugo theme [doks](https://github.com/h-enk/doks) uses the hugo-installer since the latest release.
I'm now having problems with npm install where the hugo-installer tries to download the binaries from github.

We're using a company proxy (aswell as an Artifactory instance which serves a npm registry). I've configured the HTTP and HTTPS proxy settings, however I am now getting the following error:
```
npm ERR! code 1
npm ERR! path D:\git\my-project\node_modules\@hyas\doks
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c hugo-installer --version otherDependencies.hugo --extended --destination node_modules/.bin/hugo
npm ERR! Hugo Installer
npm ERR!
npm ERR! > Checking for existing binary
npm ERR! > Downloading binary from "https://github.com/gohugoio/hugo/releases/download/v0.101.0/hugo_extended_0.101.0_Windows-64bit.zip"
npm ERR! > Downloading checksum from "https://github.com/gohugoio/hugo/releases/download/v0.101.0/hugo_0.101.0_checksums.txt"
npm ERR! > Verifying binary checksum
npm ERR! > Extracting binary to disk
npm ERR! > Verifying binary health
npm ERR! Error: spawn UNKNOWN
npm ERR!     at ChildProcess.spawn (node:internal/child_process:413:11)
npm ERR!     at spawn (node:child_process:757:9)
npm ERR!     at file:///D:/git/my-project/node_modules/hugo-installer/index.js:687:30
npm ERR!     at new Promise (<anonymous>)
npm ERR!     at verifyBinaryHealth (file:///D:/git/my-project/node_modules/hugo-installer/index.js:685:12)
npm ERR!     at installHugo (file:///D:/git/my-project/node_modules/hugo-installer/index.js:749:31) {
npm ERR!   errno: -4094,
npm ERR!   code: 'UNKNOWN',
npm ERR!   syscall: 'spawn'
npm ERR! }

```

**Comment by simonstumpf** [comment]
Sorry for the inconvenience. 
Our company blocks all executables in a specific directory (where my git project was located). 
After moving it to a different location it worked.
